### ISSUE TITLE
Who even likes bad blood?

### ISSUE THREAD

**Issue by FaizAther** [FaizAther/def-ny_se2011#4]
## Description:
I want to know when blood goes bad.

## Criteria:
Drink (fresh_blood->[Array<Blood>] )->blood first

**Comment by muqaddis710** [comment]
![Uploading Issues4.jpg…]()

**Comment by muqaddis710** [comment]
![Issues4](https://user-images.githubusercontent.com/37052857/68201441-e389e600-0015-11ea-937f-ffc4dd9d8788.jpg)

**Comment by muqaddis710** [comment]
Not completed

**Comment by muqaddis710** [comment]
Not completed

**Comment by muqaddis710** [comment]
Completed --> Added functions to storage and blood
